version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
      - "19092:19092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092, PLAINTEXT_INTERNAL://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx500M -Xmx500M"
      KAFKA_JVM_PERFORMANCE_OPTS: "-Xmx500M -Xmx500M"


#docker compose exec broker kafka-topics --create --topic data --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1


  # kafka-topics-creator:
  #   build:
  #     context: kafka-topics-creator
  #     dockerfile: dockerfile
  #   container_name: kafka-topics-creator
  #   depends_on:
  #     - zookeeper
  #     - broker
  #   environment:
  #     ZOOKEEPER_HOSTS: "zookeeper:2181"
  #     KAFKA_TOPICS: "sensor"
